### ISSUE TITLE
error when start up

### ISSUE THREAD

**Issue by swr1bm86** [mmhelloworld/fregelet#4]
after i run

```
mvn install && mvn exec:exec
```

it occurs the error

```
java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at frege.compiler.Javatypes$3.eval(Javatypes.java:321)
    at frege.compiler.Javatypes$3.eval(Javatypes.java:318)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Javatypes$5$1$1.eval(Javatypes.java:421)
    at frege.compiler.Javatypes$5$1$1.eval(Javatypes.java:418)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Javatypes$5$1.eval(Javatypes.java:442)
    at frege.compiler.Javatypes$5$1.eval(Javatypes.java:403)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Javatypes$8$1.eval(Javatypes.java:599)
    at frege.compiler.Javatypes$8$1.eval(Javatypes.java:596)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:257)
    at frege.prelude.PreludeBase$TST$1.eval(PreludeBase.java:13962)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:200)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.passes.Transdef$22$1$1.eval(Transdef.java:6313)
    at frege.compiler.passes.Transdef$22$1$1.eval(Transdef.java:6222)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Main$12$1.eval(Main.java:3359)
    at frege.compiler.Main$12$1.eval(Main.java:3328)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.types.Global$14$1.eval(Global.java:6980)
    at frege.compiler.types.Global$14$1.eval(Global.java:6924)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:200)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Main$33$1.eval(Main.java:5396)
    at frege.compiler.Main$33$1.eval(Main.java:5363)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Main$37$1.eval(Main.java:5713)
    at frege.compiler.Main$37$1.eval(Main.java:5616)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:257)
    at frege.prelude.PreludeMonad$IMonad_ST$4.eval(PreludeMonad.java:3559)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.compiler.Main$1Fasync_25495$1$1$1.eval(Main.java:6110)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.Delayed.forced(Delayed.java:267)
    at frege.runtime.WrappedCheckedException.doCatch(WrappedCheckedException.java:65)
    at frege.prelude.PreludeIO$5.eval(PreludeIO.java:1216)
    at frege.runtime.Fun1$1.eval(Fun1.java:63)
    at frege.runtime.Delayed.call(Delayed.java:198)
    at frege.runtime.SwingSupport$1.run(SwingSupport.java:56)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by swr1bm86** [comment]
does it only work with jdk8+ ?

**Comment by mmhelloworld** [comment]
yes, the maven compiler plugin is [configured](https://github.com/mmhelloworld/fregelet/blob/master/pom.xml#L31) to compile to Java 8. You could change it you want to run it on Java 7.

**Comment by swr1bm86** [comment]
:ok_hand:
